package org.acme.dynamodb;


import io.quarkus.runtime.annotations.RegisterForReflection;

@RegisterForReflection(targets = {
    software.amazon.awssdk.enhanced.dynamodb.extensions.AtomicCounterExtension.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.WriteModification.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.ReadModification.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAtomicCounter.class,
    software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute.class,
    software.amazon.awssdk.enhanced.dynamodb.internal.extensions.VersionRecordAttributeTags.class,
    software.amazon.awssdk.enhanced.dynamodb.internal.extensions.DefaultDynamoDbExtensionContext.class,
    software.amazon.awssdk.enhanced.dynamodb.internal.extensions.ChainExtension.class,
    software.amazon.awssdk.enhanced.dynamodb.internal.extensions.AtomicCounterTag.class,
    software.amazon.awssdk.enhanced.dynamodb.internal.extensions.AutoGeneratedTimestampRecordAttributeTags.class
}, ignoreNested = false)
public class ReflectionConfig {
}
